#define WINDOW_WIDTH 750
#define WINDOW_HEIGHT 600

#define PLAYER_SIZE 54

#define MAX_PROJECTILES 100
#define PROJECTILE_WIDTH 8
#define PROJECTILE_HEIGHT 20

#define MAX_ASTEROIDS 5
#define ASTEROID_SIZE 34



